
package com.inetpsa.pct00.application.service.wltp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConfigPortType", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigPortType {


    /**
     * 
     * @param config
     * @return
     *     returns com.inetpsa.pct00.application.service.wltp.ConfigResponseType
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "Config", action = "http://xml.inetpsa.com/Services/Cfg/Config#Config")
    @WebResult(name = "ConfigResponse", targetNamespace = "http://inetpsa.com/cfg")
    @RequestWrapper(localName = "Config", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config", className = "com.inetpsa.pct00.application.service.wltp.Config")
    @ResponseWrapper(localName = "ConfigResponse", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config", className = "com.inetpsa.pct00.application.service.wltp.ConfigResponse")
    public ConfigResponseType config(
        @WebParam(name = "Config", targetNamespace = "http://inetpsa.com/cfg")
        ConfigType config)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param configFeature
     * @return
     *     returns com.inetpsa.pct00.application.service.wltp.ConfigFeatureResponseType
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "ConfigFeature", action = "http://xml.inetpsa.com/Services/Cfg/Config#ConfigFeature")
    @WebResult(name = "ConfigFeatureResponse", targetNamespace = "http://inetpsa.com/cfg")
    @RequestWrapper(localName = "ConfigFeature", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config", className = "com.inetpsa.pct00.application.service.wltp.ConfigFeature")
    @ResponseWrapper(localName = "ConfigFeatureResponse", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config", className = "com.inetpsa.pct00.application.service.wltp.ConfigFeatureResponse")
    public ConfigFeatureResponseType configFeature(
        @WebParam(name = "ConfigFeature", targetNamespace = "http://inetpsa.com/cfg")
        ConfigFeatureType configFeature)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param config
     * @return
     *     returns com.inetpsa.pct00.application.service.wltp.ConfigResponseTypeV2
     * @throws ServiceException_Exception
     */
    @WebMethod(operationName = "ConfigV2", action = "http://xml.inetpsa.com/Services/Cfg/Config#ConfigV2")
    @WebResult(name = "ConfigResponseV2", targetNamespace = "http://inetpsa.com/cfg")
    @RequestWrapper(localName = "ConfigV2", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config", className = "com.inetpsa.pct00.application.service.wltp.ConfigV2")
    @ResponseWrapper(localName = "ConfigV2Response", targetNamespace = "http://xml.inetpsa.com/Services/Cfg/Config", className = "com.inetpsa.pct00.application.service.wltp.ConfigV2Response")
    public ConfigResponseTypeV2 configV2(
        @WebParam(name = "Config", targetNamespace = "http://inetpsa.com/cfg")
        ConfigType config)
        throws ServiceException_Exception
    ;

}
